### ISSUE TITLE
Critical CSS seems to be broken

### ISSUE THREAD

**Issue by earcos** [o10n-x/wordpress-css-optimization#1]
Hi, as I stated on the other plugin forum, I'm trying the new plugins 😄 

So, this is the first bug I have encountered. The Critical CSS section is not really working. Here's a screenshot of what I am seeing and the error I get when I try to save a new file. I think it is not loading all text inputs correctly.

![screenshot 2018-03-11 01 16 32](https://user-images.githubusercontent.com/16387856/37248156-31dd2638-24ca-11e8-9ebf-50c1e50e0f2b.jpg)

**Comment by optimalisatie** [comment]
Thank you very much for your feedback and help with testing the new plugins!

It is correct that more fields should have been visible.

![image](https://user-images.githubusercontent.com/8843669/37250673-56925c0e-2502-11e8-981f-ab9566a1806e.png)

We have improved the form in the latest update `v0.0.25`.

![image](https://user-images.githubusercontent.com/8843669/37251439-4d497142-2510-11e8-9f95-bb24b8ef12fe.png)

We will soon add unit tests to test the admin functionality such as adding a critical CSS file using many browsers and mobile devices.

**Comment by earcos** [comment]
I can see the new interface, much better, but I have a new problem. The "Add file" button is not working, is not doing anything 😢 

Here's a screenshot. I used the inspector if there's an error when clicking on the button, but nothing whatsoever.

![screen shot 2018-03-12 at 14 08 35](https://user-images.githubusercontent.com/16387856/37285345-10373f10-25ff-11e8-86fb-b10d525c364e.png)

**Comment by optimalisatie** [comment]
Thank you very much for your help with testing!

The issue may be related to the browser cache (admin client script). Could you please try to load the admin with cache disabled? (F12 -> Network)

![image](https://user-images.githubusercontent.com/8843669/37285768-60bcdf70-2600-11e8-9dd4-6467ca9d4976.png)

The latest plugin update contains a JSON profile based configuration editor. This is the true innovation and strength of the new plugin. It will be possible to discuss optimization configuration on public forums to receive expert advise and it will be possible to quickly copy and paste a proven optimization configuration to a new website, so it will save optimization specialists literally tons of time while the plugin allows to achieve the absolute best performance result possible (no concessions on performance in favor of easy management while management is more efficient using JSON profiles).

The complete configuration is JSON based. The WordPress database/options are never needed. It makes the optimization technology sort of independent from WordPress. It also makes it reliable on the long term with over 10,000 real optimization options.

The quick bridge concept does use WordPress options for storing JSON, but as you can see it can still be managed as a JSON profile using the editor.

**Comment by earcos** [comment]
Is not working with disabled cache 😕

The JSON configuration is a great addition! 

Thanks again for your help

**Comment by earcos** [comment]
Ok, this is working now, so I'll close it :)
