### ISSUE TITLE
i have also this issue

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-css-optimization#10]
LocalStorage Cache

if i set a value, and want to comeback to default value it do not comeback to original value.
![capture](https://user-images.githubusercontent.com/21690761/39418901-0c9af548-4c2b-11e8-94f3-5aa898485b5b.PNG)

i tried to use the json value from an other site where i used your plugin also and it update the value it's seems that the json don't update or it's both.

like those value are store at someplace and if we remove them it keep getting writte back and then the json don't update.

**Comment by optimalisatie** [comment]
Hi Maxime,

Thank you very much for reporting the bug! The issue has been resolved in `v0.0.67`.
