### ISSUE TITLE
how to exclude admin css

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-css-optimization#11]
Hiya.
I am using the current version of CSS optimiser.
My TinyMCE editor in posts etc is borked since I enabled delivery optimisation.
Is there any way to exclude the CSS for the admin area?
Thanks!

**Comment by optimalisatie** [comment]
Hi ProductivePhysician,

Thank you for providing feedback!

The plugin should not perform any optimization in the admin panel. Could you please provide a screenshot of the issue?

**Comment by ProductivePhysician** [comment]
Never mind, I don't think it's the plugin, I think it's some custom CSS
rule I created.
Sorry :)
