### ISSUE TITLE
i got this error.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-css-optimization#12]
i don't know why i didn't had this error since a lon time.

GET https://max-mad.com/wp-content/cache/o10n/css/src/65/4d/fonts/fontawesome-webfont.woff2?v=4.6.3 404 ()
3(index):1 GET https://max-mad.com/wp-content/cache/o10n/css/src/65/4d/fonts/fontawesome-webfont.woff?v=4.6.3 404 ()

**Comment by optimalisatie** [comment]
It means that there is an issue with URL rebasing.

Did you enable the URL rebase option?

![image](https://user-images.githubusercontent.com/8843669/39677299-e70b2f3e-5178-11e8-855e-9511d696b6f1.png)

If you are using the URL rebase option then it means that for some reason the font awesome fonts are still relatively linked in the CSS. It will then be required to convert the font URLs manually. You could use the CSS code search & replace feature or you could manually edit the CSS source files.

![image](https://user-images.githubusercontent.com/8843669/39677328-5036b9ec-5179-11e8-91c3-7f255445ea34.png)
