### ISSUE TITLE
AMP markup missing or incorrect

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-css-optimization#14]
Hi again,
Sorry to pester with another issue.
Using the CSS optimisation plugin, I am getting an AMP error: AMP markup missing or incorrect.
See: https://search.google.com/test/amp?id=B3pCDjHsBcCL7Xe0SaO8Cg
The AMP test page at Google is assigning this error to the <style data-o10n="critical"> line in my page, although I'm not sure this is true.
Can you give me any advice?
Cheers!

**Comment by ProductivePhysician** [comment]
Scratch that... I added the hook found in this thread (https://github.com/o10n-x/wordpress-javascript-optimization/issues/2) to my functions.php and it no longer throws an error.

Thanks!

**Comment by optimalisatie** [comment]
Thank you very much for providing feedback!

We have added additional options to disable the optimization in the latest update `v0.0.68`.

https://github.com/o10n-x/wordpress-css-optimization/releases/tag/0.0.68

You can follow the release information from Github > Releases.

**Comment by ProductivePhysician** [comment]
Where is the option in the UI? I can't see it but I'm sure it's there :)

**Comment by AlphaDE** [comment]
Same here, could you please make that configurable in the UI so it is possible without modifying different themes and many sites manually?
