### ISSUE TITLE
Custom admin menu no longer working

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-css-optimization#15]
Hi again.
I don't know if this is related to using your plugins, but I have a script in my functions.php that re-orders my admin menu.
This is no longer working.
I only have css, js and http/2 plugins installed so far.
Is it likely that any of these will conflict with my re-ordering my admin?
Cheers!

**Comment by ProductivePhysician** [comment]
Hi team, any suggestions?

**Comment by optimalisatie** [comment]
Hi ProductivePhysician,

Our apologies for the late reply!

We are not certain what may cause the issue that you describe. Could you please post the custom code that you use for re-ordering the menu? We will then investigate the issue.
