### ISSUE TITLE
JS error when trying to generate critical CSS

### ISSUE THREAD

**Issue by pratham2003** [o10n-x/wordpress-css-optimization#16]
In chrome.
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules.

In firefox.
SecurityError: The operation is insecure.

**Comment by optimalisatie** [comment]
The widget works in Chrome 62. The widget is based on a concept by Paul Kinlan, head of Chrome webdeveloper relations team. 

https://gist.github.com/PaulKinlan/6284142

The original snippet uses a Chrome innovation called `getMatchedCSSRules` which is deprecated and will be removed in Chrome 63. The Critical CSS Widget is made cross browser using a polyfill for `getMatchedCSSRules`. It may be that your browser does not support it.

![image](https://user-images.githubusercontent.com/8843669/36543121-1da8cc7e-17e3-11e8-8ed1-a7f69b47757c.png)

**Comment by pratham2003** [comment]
Same error with the above script.

I tried the following
```
(function(d,c,s) {s=d.createElement('script');s.async=true;s.onload=c;s.src='https://cdn.rawgit.com/o10n-x/critical-css-widget/master/critical-css-widget.min.js';d.head.appendChild(s);})(document,function() {
   // critical css file download
   o10n.extract();
});
```

The issue is that there are some link[rel=stylesheet] tags linking to external domains, hence the security related error. In my case these link tags are google fonts and some push notification widget.

Can we in some way limit the link tags picked up to the current domain?
or remove the link tags via javascript before we run the above script?
```
jQuery('link[rel=stylesheet]').each(function(){ if(jQuery(this).attr('href').indexOf(location.hostname) == -1){ console.log("Removed : " + jQuery(this).attr('href')); jQuery(this).remove(); } });
```

**Comment by optimalisatie** [comment]
The issue (security warning) is not present in Chrome.

It may be best to simply use Google Chrome as the innovation it uses originates from Google Chrome. 

Ultimately, external stylesheets should not be ignored but supported. A professional critical CSS solution may be a better option, we may release a API service for it soon.

**Comment by optimalisatie** [comment]
We have updated the widget with an improvement that should ignore the error.

https://github.com/o10n-x/critical-css-widget/releases/tag/1.0.2
