### ISSUE TITLE
i'm having this 3 error.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-css-optimization#17]
![image](https://user-images.githubusercontent.com/21690761/40649047-eff81abc-62fd-11e8-9f5c-c9290e1ee78f.png)

like 

![image](https://user-images.githubusercontent.com/21690761/40649118-168c6728-62fe-11e8-802c-6797b2d2a770.png)

i cannot set a bolean for css critical minify since it's a checkbox.

and this error.

.css.critical.minify.cssmin.filters.ImportImports | should be object
-- | --

i leave the config as you set them.

  | .css.critical.minify | should match exactly one schema in oneOf

i guess i cannot set it since it use 
 PHP CssMin as default value

if i understand it clearly

**Comment by optimalisatie** [comment]
The critical CSS minify option will be removed in a future version or improved to use the new minifier modules.

It may be best to use CleanCSS using the CSS editor. It should provide a much better result than a PHP minifier.
