### ISSUE TITLE
compressed .css not served from CDN although configured

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-css-optimization#18]
Jan,

I just noticed that despite I configured a CDN (static.mydomain.de) in the CSS delivery options, the compressed .css are delivered from the main domain

GET
https://www.mydomain.de/wp-content/cache/o10n/css/0/1/2.css
[HTTP/1.1 200 OK 125ms]
GET
https://www.mydomain.de/wp-content/cache/o10n/css/0/1/3.css
[HTTP/1.1 200 OK 372ms]
GET
https://www.mydomain.de/wp-content/cache/o10n/css/0/1/1.css

Anything I missed to configure?

Btw. how can I removed a useless query string from a static ressource

https://static.mydomain.de/wp-co ... -awesome/fonts/fontawesome-webfont.woff2?v=4.7.0

**Comment by optimalisatie** [comment]
The issue has been fixed in the latest update.

https://github.com/o10n-x/wordpress-css-optimization/releases/tag/0.0.78
