### ISSUE TITLE
multiple 403 errors in wp-admin/admin.php?page=o10n-css&tab=optimization

### ISSUE THREAD

**Issue by azirer** [o10n-x/wordpress-css-optimization#21]
Should I be worried? What exactly happens?

![error](https://user-images.githubusercontent.com/8659548/41229541-173cc226-6d85-11e8-834a-2566a51db9fd.jpg)

Thank you

**Comment by optimalisatie** [comment]
Hi Azirer,

Thank you for the feedback!

The issue that you experience is related to Github Buttons using an non-cached Github API request to get the counts for buttons, resulting in a Github IP ban (403 error).

We've discussed the issue thoroughly but the author intends to leave the responsibility to users. 

https://github.com/ntkme/github-buttons/issues/33

The Github IP ban normally only occurs when you disable the browser cache (e.g. when using the Developer Tools).

If you seek a solution it would be best to contact the author of Github Buttons:

https://github.com/ntkme/github-buttons/issues/33

**Comment by azirer** [comment]
Thank you
