### ISSUE TITLE
Issue with super cache which creates a Cache-Control: max-age=3 in /wp-content/cache/

### ISSUE THREAD

**Issue by azirer** [o10n-x/wordpress-css-optimization#22]
I use Super Cache (Do you recommend an alternative that works fine with your plugins and serves static files?) Super Cache unfortunately does this https://github.com/Automattic/wp-super-cache/issues/523 and places the htaccess file inside `/wp-content/cache/ `

So is it safe for us to place another htaccess file in `/wp-content/cache/o10n/` for our static resources or your plugins will delete that file eventually during a cache clear?

Any other ideas?

**Comment by optimalisatie** [comment]
You can change the cache directory using the constant `O10N_CACHE_DIR`.

The WPO collection also contains a static file cache that is able to provide much better performance than other static file cache plugins (physically up to 100x increased speed on a cheap 1 core VPS) using PHP Opcache (memory cache without serialization or startup overhead).

The advantage of the plugin when using PHP Opcache is that there is absolutely zero file IP (no disk usage). The full page would load from RAM memory. In the same time it supports PHP logic to enable conditional requests (`304 Not Modified`) and advanced cache configuration (using JSON).

A unique feature is that it supports caching of dynamic content. It allows to configure a custom cache hash that can be based on PHP conditional methods such as `is_user_logged_in` or the user ID, `get_current_user_id`.

When using PHP Opcache, the cache is as fast as it can be in PHP.

Cache speed (full cache process time) on a 1-core VPS: 60μs (0.06ms or 0.00006 seconds). No file IO!

![image](https://user-images.githubusercontent.com/8843669/41279756-9b99153a-6e2d-11e8-8460-448614d7cc10.png)

https://github.com/o10n-x/wordpress-file-page-cache

You can install the plugin with a single click from the WPO admin panel.

![image](https://user-images.githubusercontent.com/8843669/41279989-2d923df4-6e2e-11e8-9322-950faf4aec3d.png)

**Comment by azirer** [comment]
I changed the super cache folder instead, Thank you I will try your cache as well.
