### ISSUE TITLE
PHP Warning:  preg_match(): Unknown modifier '/'

### ISSUE THREAD

**Issue by ahmed-sigmalux** [o10n-x/wordpress-css-optimization#25]
The following CSS URL filter passes the JSON editor and a regex tester:

`[{"url":"/^https://www\\.mydomain(s)?\\.[a-z]{2,3}([a-z]{2})?(.+)$/i","regex":true,"replace":"$3"}]`

But doesn't work and generates an error in the debug.log:

`PHP Warning:  preg_match(): Unknown modifier '/' in /var/www/mydomain/wordpress/extensions/wordpress-css-optimization/controllers/css.class.php on line 1367`

**Comment by optimalisatie** [comment]
Hi Ahmed,

Thank you for taking the time to report the issue!

Regular expressions in JSON configuration are not yet verified in the admin. This will be added in the future.

For now you are responsible for the validity of regular expressions.

In regards to the regular expression. It is invalid. `https://` contains the delimiter and should be escaped:

```regexp
/^https:\/\/www\.mydomain(s)?\.[a-z]{2,3}([a-z]{2})?(.+)$/i
```

Tip: you can easily test a regular expression by entering it in the browser console:

![image](https://user-images.githubusercontent.com/8843669/41452344-cf38356a-7071-11e8-8390-cf49f7a6d879.png)

```javascript
// test regular expression
/^https:\/\/www\.mydomain(s)?\.[a-z]{2,3}([a-z]{2})?(.+)$/i.test('pattern to test');
```

Your JSON would become:

```json
[
  {
    "url": "/^https:\\/\\/www\\.mydomain(s)?\\.[a-z]{2,3}([a-z]{2})?(.+)$/i",
    "regex": true,
    "replace": "$3"
  }
]
```
