### ISSUE TITLE
Question about critical priorities and rules

### ISSUE THREAD

**Issue by azirer** [o10n-x/wordpress-css-optimization#27]
Priority 1 means takes place before priority 2? Or is it the opposite?

What about the critical css that doesn't fall in any of the specified conditions? Should I create a general rule like is_page() & is_post and assign the lowest priority?

**Comment by optimalisatie** [comment]
Hi @azirer,

Again our apologies for the late answer.

A higher priority is included in the HTML later, thus overruling critical CSS with a lower priority.

![image](https://user-images.githubusercontent.com/8843669/45863554-e88ac800-bd76-11e8-9662-02cdf53f7c46.png)

When leaving the conditions blank, the critical CSS will be included on all pages. It would be an option for example to create a critical CSS entry for webfonts. This makes it more easy to manage.
