### ISSUE TITLE
Groups & group dependency on other concatenated group?

### ISSUE THREAD

**Issue by azirer** [o10n-x/wordpress-css-optimization#30]
My first question is does the order of the scripts inside the JSON defines the order of appearance of the specific styles inside global-group.css 

The second question is how can I make sure that the sec group should be loaded after the global-group?

In CSS Code Optimization I have
```[
  {
    "match": [
      "stt.min.css", 
      "main.min.css", 
      "js_composer_front_custom.css",
      "post-type.css",
      "custom.css",
      "media.css",
      "post-type-dynamic.css",
      {
        "string": ".*child-theme.*",
        "regex": true
      },
      "style.min.css",
      {
        "string": ".*fonts.googleapis.com.*",
        "regex": true
      }
    ],
    "group": {
      "title": "global-group",
      "key": "global-group",
      "id": "global-group"
    },
    "minify": true
  },
  {
    "match": [
      "fancytext.min.css",
      "background-style.min.css",
      "animate.min.css",
      "tooltip.min.css"
    ],
    "group": {
      "title": "sec-group",
      "key": "sec-group",
      "id": "sec-group"
    },
    "minify": true
  }
]
```

I tried to inject a dependency attribute in the above code something like 
```
{
    "match": [
      "fancytext.min.css",
      "background-style.min.css",
      "animate.min.css",
      "tooltip.min.css"
    ],
    "group": {
      "title": "sec-group",
      "key": "sec-group",
      "id": "sec-group"
    },
	"dependency": "global-group",
    "minify": true
  }
```

but I get an error in the editor. 

Third question is why the style `https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C600&subset=latin-ext&ver=4.9.6` creates a group on its own with the above configuration and is not included in the global-group?

**Comment by optimalisatie** [comment]
Hi @azirer,

Our apologies for not answering your questions promptly. 

1) no, the original order of `wp_enqueue_script` is preserved. The JSON configuration contains just matching rules. You can however define dependency configuration which can enable to execute scripts in a desired order.

2) CSS concatenation does not have the `dependency` option yet. We have added it to the list and will add it in a next update.

Your JSON for dependency based stylesheet loading was correct.

3) a regular expression requires the full format, not just the inner part. `fonts.googleapis.com` is therefor not matched. A correct regular expression would be `/.*fonts\.googleapis.com\.*/`. Also note that when writing an escape character within JSON `"..."` you need to double escape it, in this case `"/.*fonts\\.googleapis.com\\.*/"`.
