### ISSUE TITLE
Critical css extraction shows the following error - DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by tjackadams** [o10n-x/wordpress-css-optimization#33]
When trying to extract the critical css i get the following exception in the browser console.

> Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
>     at b (http://www.nottinghamtutorialcollege.co.uk/wp-content/cache/o10n/js/src/a4/4b/b3/cf355befe8e64bbce91777c04d.js:2:2229)
>     at http://www.nottinghamtutorialcollege.co.uk/wp-content/plugins/wordpress-css-optimization/public/js/critical-css-widget.min.js:6:131
>     at new y (http://www.nottinghamtutorialcollege.co.uk/wp-content/plugins/wordpress-css-optimization/public/js/critical-css-widget.min.js:6:190)
>     at qa.w.extract (http://www.nottinghamtutorialcollege.co.uk/wp-content/plugins/wordpress-css-optimization/public/js/critical-css-widget.min.js:13:348)
>     at HTMLScriptElement.n.onload (http://www.nottinghamtutorialcollege.co.uk/wp-content/plugins/wordpress-css-optimization/public/js/view-css-editor-iframe.js:1:463)

any suggestions how i can troubleshoot this further?

**Comment by optimalisatie** [comment]
Hi tjackadams,

Thank you for your feedback! It is very valuable and it will improve the quality of the plugins!

In regards to the issue, the critical CSS extract widget is published as a separate Github repo. It is not directly related to the plugin.

https://github.com/o10n-x/critical-css-widget

The Critical CSS extract widget is based on a concept by Paul Kinlan, head of Chrome webdeveloper relations team.

https://gist.github.com/PaulKinlan/6284142

The original snippet uses a Chrome innovation called `getMatchedCSSRules` which is deprecated and has been removed in Chrome 63 (current version is 69).

The Critical CSS Widget is made cross browser using a [polyfill](https://github.com/ovaldi/getMatchedCSSRules) for `getMatchedCSSRules`.

It seems to work well, even in Firefox, but it may be that for some reason it doesn't work in your browser (version).

Could you please let us know what browser/version you are using? And (if not Chrome) could you try it in Google Chrome?

You can copy & paste the following code in the browser console to instantly extract the critical CSS for a page. It is the same widget as included in the CSS optimization plugin but hosted via Github.

```javascript
(function(d,c,s) {s=d.createElement('script');s.async=true;s.onload=c;s.src='https://cdn.rawgit.com/o10n-x/critical-css-widget/master/critical-css-widget.min.js';d.head.appendChild(s);})(document,function() {
   // critical css file download
   o10n.extract();
});
```

**Comment by tjackadams** [comment]
Hi @optimalisatie ,

Apologies, i didn't realise that the extract widget was apart of another repository. I would close this issue and re-raise it there but it appears to be resolved.

i was running this version of Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
but after updating to the latest version Version 68.0.3440.106 (Official Build) (64-bit) i can successfully run the widget.

There is just one more point i would like to mention, it may be the fact i am doing something incorrect at my side, or a potential improvement for the plugin.

As i understand it, you have to be logged in to use the widget (although the function you sent does not require this). Is there anyway we can strip the wordpress admin bar styles from the critical css without manually editing it?
If not then it doesn't really matter, i am fine with manually editing the css generated, i just thought i would mention it.
