### ISSUE TITLE
Uncaught Error: <script data-o10n>

### ISSUE THREAD

**Issue by Tainq** [o10n-x/wordpress-css-optimization#36]
Uncaught Error: <script data-o10n>
    at VM5035:2
    at VM5035:17
When enable Minify JS/CSS

**Comment by Tainq** [comment]
After update JQMIGRATE version 3.0.0 all good

**Comment by optimalisatie** [comment]
Hi @Tainq,

Thank you for the feedback!

Our apologies for not responding before. The plugin has received many updates in the past months. No other user has reported the issue until now. Our advise is to try the latest version if you still want to make use of the plugin.

https://github.com/o10n-x/wordpress-css-optimization/releases
