### ISSUE TITLE
hello i got this error.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-css-optimization#7]
File: [ABSPATH]wp-content/plugins/wordpress-css-optimization-master/core/controllers/client.class.php
File: [ABSPATH]wp-content/plugins/wordpress-css-optimization-master/core/controllers/core.class.php Line: 197

**Comment by optimalisatie** [comment]
Hi Maxime,

Thanks again for reporting the issue! It was a small bug related to the Service Worker maximum cache size. 

The issue has been resolved in `v0.0.12`.
